"""refactor monsters + add movement/sense/language

Revision ID: 06a4c94ff971
Revises: c791f1b36e44
Create Date: 2025-08-15 19:02:09.862962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a4c94ff971'
down_revision: Union[str, Sequence[str], None] = 'c791f1b36e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
