"""add monster_movement table

Revision ID: 13b36db86a2c
Revises: b451d8197f6f
Create Date: 2025-08-15 18:02:42.147996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13b36db86a2c'
down_revision: Union[str, Sequence[str], None] = 'b451d8197f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster_movement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monster_id', 'movement_type', name='uq_movement_per_monster')
    )
    op.create_index(op.f('ix_monster_movement_monster_id'), 'monster_movement', ['monster_id'], unique=False)
    op.drop_column('monsters', 'speeds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('speeds', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_monster_movement_monster_id'), table_name='monster_movement')
    op.drop_table('monster_movement')
    # ### end Alembic commands ###
