"""initial_schema

Revision ID: 73e30fb7335d
Revises: 
Create Date: 2026-01-12 00:01:11.519884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73e30fb7335d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'DM', 'PLAYER', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_approval_pending', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('github_id', name=op.f('uq_users_github_id')),
    sa.UniqueConstraint('google_id', name=op.f('uq_users_google_id')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_is_approval_pending'), 'users', ['is_approval_pending'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('monsters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('challenge_rating', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('xp_override', sa.Integer(), nullable=True),
    sa.Column('armor_class_text', sa.String(length=200), nullable=False),
    sa.Column('passive_perception', sa.Integer(), nullable=False),
    sa.Column('telepathy_range', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=False),
    sa.Column('main_type', sa.String(length=64), nullable=False),
    sa.Column('subtype', sa.String(length=128), nullable=True),
    sa.Column('alignment', sa.String(length=32), nullable=False),
    sa.Column('hit_points', sa.Integer(), nullable=False),
    sa.Column('hit_points_dice', sa.String(length=50), nullable=False),
    sa.Column('str_score', sa.Integer(), nullable=False),
    sa.Column('dex_score', sa.Integer(), nullable=False),
    sa.Column('con_score', sa.Integer(), nullable=False),
    sa.Column('int_score', sa.Integer(), nullable=False),
    sa.Column('wis_score', sa.Integer(), nullable=False),
    sa.Column('cha_score', sa.Integer(), nullable=False),
    sa.Column('saving_throw_proficiencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_proficiencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bonus_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legendary_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lair_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regional_effects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.CheckConstraint("btrim(armor_class_text) <> ''", name=op.f('ck_monsters_armor_class_nonblank')),
    sa.CheckConstraint('\n            (challenge_rating = 0 AND (xp_override IN (0, 10) OR xp_override IS NULL))\n            OR (challenge_rating <> 0 AND xp_override IS NULL)\n            ', name=op.f('ck_monsters_xp_override_valid')),
    sa.CheckConstraint('\n            challenge_rating IN (\n                0,\n                0.125, 0.25, 0.5,\n                1, 2, 3, 4, 5, 6, 7, 8, 9, 10,\n                11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n                21, 22, 23, 24, 25, 26, 27, 28, 29, 30\n            )\n            ', name=op.f('ck_monsters_challenge_rating_allowed')),
    sa.CheckConstraint('cha_score BETWEEN 1 AND 30', name=op.f('ck_monsters_cha_1_30')),
    sa.CheckConstraint('con_score BETWEEN 1 AND 30', name=op.f('ck_monsters_con_1_30')),
    sa.CheckConstraint('dex_score BETWEEN 1 AND 30', name=op.f('ck_monsters_dex_1_30')),
    sa.CheckConstraint('hit_points > 0', name=op.f('ck_monsters_hit_points_positive')),
    sa.CheckConstraint('int_score BETWEEN 1 AND 30', name=op.f('ck_monsters_int_1_30')),
    sa.CheckConstraint('passive_perception >= 0', name=op.f('ck_monsters_passive_perception_nonneg')),
    sa.CheckConstraint('str_score BETWEEN 1 AND 30', name=op.f('ck_monsters_str_1_30')),
    sa.CheckConstraint('telepathy_range > 0', name=op.f('ck_monsters_telepathy_range_pos')),
    sa.CheckConstraint('wis_score BETWEEN 1 AND 30', name=op.f('ck_monsters_wis_1_30')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_monsters_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monsters'))
    )
    op.create_index(op.f('ix_monsters_alignment'), 'monsters', ['alignment'], unique=False)
    op.create_index(op.f('ix_monsters_challenge_rating'), 'monsters', ['challenge_rating'], unique=False)
    op.create_index(op.f('ix_monsters_is_official'), 'monsters', ['is_official'], unique=False)
    op.create_index(op.f('ix_monsters_main_type'), 'monsters', ['main_type'], unique=False)
    op.create_index(op.f('ix_monsters_owner_id'), 'monsters', ['owner_id'], unique=False)
    op.create_index(op.f('ix_monsters_size'), 'monsters', ['size'], unique=False)
    op.create_index('uq_monsters_lower_name', 'monsters', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('csrf_secret', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('monster_condition_immunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_condition_immunities_monster_id_monsters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_condition_immunities')),
    sa.UniqueConstraint('monster_id', 'condition', name='uq_condition_per_monster')
    )
    op.create_index('ix_monster_condition_immunities_condition', 'monster_condition_immunities', ['condition'], unique=False)
    op.create_table('monster_damage_immunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('damage_type', sa.String(length=16), nullable=False),
    sa.CheckConstraint("damage_type IN ('Acid','Bludgeoning','Cold','Fire','Force','Lightning','Necrotic','Piercing','Poison','Psychic','Radiant','Slashing','Thunder')", name=op.f('ck_monster_damage_immunities_ck_damage_immunity_type')),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_damage_immunities_monster_id_monsters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_damage_immunities')),
    sa.UniqueConstraint('monster_id', 'damage_type', name='uq_immunity_per_monster_type')
    )
    op.create_index('ix_monster_damage_immunities_damage_type', 'monster_damage_immunities', ['damage_type'], unique=False)
    op.create_table('monster_damage_resistances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('damage_type', sa.String(length=16), nullable=False),
    sa.CheckConstraint("damage_type IN ('Acid','Bludgeoning','Cold','Fire','Force','Lightning','Necrotic','Piercing','Poison','Psychic','Radiant','Slashing','Thunder')", name=op.f('ck_monster_damage_resistances_ck_damage_resistance_type')),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_damage_resistances_monster_id_monsters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_damage_resistances')),
    sa.UniqueConstraint('monster_id', 'damage_type', name='uq_resistance_per_monster_type')
    )
    op.create_index('ix_monster_damage_resistances_damage_type', 'monster_damage_resistances', ['damage_type'], unique=False)
    op.create_table('monster_damage_vulnerabilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('damage_type', sa.String(length=16), nullable=False),
    sa.CheckConstraint("damage_type IN ('Acid','Bludgeoning','Cold','Fire','Force','Lightning','Necrotic','Piercing','Poison','Psychic','Radiant','Slashing','Thunder')", name=op.f('ck_monster_damage_vulnerabilities_ck_damage_vulnerability_type')),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_damage_vulnerabilities_monster_id_monsters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_damage_vulnerabilities')),
    sa.UniqueConstraint('monster_id', 'damage_type', name='uq_vulnerability_per_monster_type')
    )
    op.create_index('ix_monster_damage_vulnerabilities_damage_type', 'monster_damage_vulnerabilities', ['damage_type'], unique=False)
    op.create_table('monster_languages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_languages_monster_id_monsters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_languages')),
    sa.UniqueConstraint('monster_id', 'language', name='uq_language_per_monster')
    )
    op.create_index('ix_monster_languages_language', 'monster_languages', ['language'], unique=False)
    op.create_table('monster_movement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('hover', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('speed >= 0', name=op.f('ck_monster_movement_speed_nonneg')),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_movement_monster_id_monsters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_movement')),
    sa.UniqueConstraint('monster_id', 'movement_type', name='uq_movement_per_monster')
    )
    op.create_index('ix_monster_movement_movement_type', 'monster_movement', ['movement_type'], unique=False)
    op.create_table('monster_senses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('sense', sa.String(length=32), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.CheckConstraint('range >= 0', name=op.f('ck_monster_senses_range_nonneg')),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_senses_monster_id_monsters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monster_senses')),
    sa.UniqueConstraint('monster_id', 'sense', name='uq_sense_per_monster')
    )
    op.create_index('ix_monster_senses_sense', 'monster_senses', ['sense'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monster_senses_sense', table_name='monster_senses')
    op.drop_table('monster_senses')
    op.drop_index('ix_monster_movement_movement_type', table_name='monster_movement')
    op.drop_table('monster_movement')
    op.drop_index('ix_monster_languages_language', table_name='monster_languages')
    op.drop_table('monster_languages')
    op.drop_index('ix_monster_damage_vulnerabilities_damage_type', table_name='monster_damage_vulnerabilities')
    op.drop_table('monster_damage_vulnerabilities')
    op.drop_index('ix_monster_damage_resistances_damage_type', table_name='monster_damage_resistances')
    op.drop_table('monster_damage_resistances')
    op.drop_index('ix_monster_damage_immunities_damage_type', table_name='monster_damage_immunities')
    op.drop_table('monster_damage_immunities')
    op.drop_index('ix_monster_condition_immunities_condition', table_name='monster_condition_immunities')
    op.drop_table('monster_condition_immunities')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('uq_monsters_lower_name', table_name='monsters')
    op.drop_index(op.f('ix_monsters_size'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_owner_id'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_main_type'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_is_official'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_challenge_rating'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_alignment'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_approval_pending'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
