"""monster: proficiencies, speeds, senses, languages, damage/condition fields

Revision ID: ac15abcc2e83
Revises: d0dc385649af
Create Date: 2025-08-15 16:52:42.669789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac15abcc2e83'
down_revision: Union[str, Sequence[str], None] = 'd0dc385649af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
