"""trim monsters and add movement/sense/language relations

Revision ID: b093f6331d2b
Revises: e6a15beb1577
Create Date: 2025-08-15 18:41:07.554471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b093f6331d2b'
down_revision: Union[str, Sequence[str], None] = 'e6a15beb1577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
