"""finalize monster model + owner relationship

Revision ID: b451d8197f6f
Revises: 23c6b7272302
Create Date: 2025-08-15 17:41:59.344012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b451d8197f6f'
down_revision: Union[str, Sequence[str], None] = '23c6b7272302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('monsters', sa.Column('spellcasting', sa.Text(), nullable=True))
    op.add_column('monsters', sa.Column('innate_spellcasting', sa.Text(), nullable=True))
    op.add_column('monsters', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('monsters', sa.Column('is_official', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_monsters_is_official'), 'monsters', ['is_official'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monsters_is_official'), table_name='monsters')
    op.drop_column('monsters', 'is_official')
    op.drop_column('monsters', 'image_url')
    op.drop_column('monsters', 'innate_spellcasting')
    op.drop_column('monsters', 'spellcasting')
    op.drop_column('monsters', 'skills')
    # ### end Alembic commands ###
