"""refactor monsters table + add movement/sense/language tables

Revision ID: c791f1b36e44
Revises: b093f6331d2b
Create Date: 2025-08-15 18:55:10.311657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c791f1b36e44'
down_revision: Union[str, Sequence[str], None] = 'b093f6331d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
