"""add monster_languages table; replace scalar languages

Revision ID: de0dcaf12de3
Revises: f8d2604e5947
Create Date: 2025-08-15 18:14:31.314589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0dcaf12de3'
down_revision: Union[str, Sequence[str], None] = 'f8d2604e5947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monsters', 'languages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('languages', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
