"""add monster_senses table; replace JSONB senses with relation

Revision ID: f8d2604e5947
Revises: 13b36db86a2c
Create Date: 2025-08-15 18:09:03.896188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8d2604e5947'
down_revision: Union[str, Sequence[str], None] = '13b36db86a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster_senses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('sense', sa.String(length=32), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monster_id', 'sense', name='uq_sense_per_monster')
    )
    op.create_index(op.f('ix_monster_senses_monster_id'), 'monster_senses', ['monster_id'], unique=False)
    op.drop_column('monsters', 'senses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('senses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_monster_senses_monster_id'), table_name='monster_senses')
    op.drop_table('monster_senses')
    # ### end Alembic commands ###
